### ISSUE TITLE
create business logic

### ISSUE THREAD

**Issue by mana8100** [LTsoft-repo/UoR-KristenCookies#1]
## ToDo
- [x] Create business layer for Kristen's cookies business.
- [x] Make sure that only Kristen has access to the business information.
- [x] Store:
  - [x] Cookies.
  - [x] Orders.
  - [x] List of customers with email.
- [x] Show:
  - [x] List of cookies.
  - [x] List of orders.
  - [x] List of customers.

**Comment by mana8100** [comment]
Closed by #4
