### ISSUE TITLE
Create reports

### ISSUE THREAD

**Issue by mana8100** [LTsoft-repo/UoR-KristenCookies#2]
## ToDo
- [ ] Report:
    - [ ] Number of orders for the week.
    - [ ] Rank of most popular mix-ins.
    - [ ] Most popular hours of the week.
